@extends('layouts.container')

@section('title', 'Edit Announcement')

@section('page_js')
    <script type="text/javascript">
        $(function() {
            $('#navbarVerticalMenu').find('#announcement-index').addClass('active');

            const form = document.getElementById('announcementUpdateForm');
            const fv = FormValidation.formValidation(form, {
                fields: {
                    title: {
                        validators: {
                            notEmpty: {
                                message: 'The title is required.'
                            }
                        }
                    },
                    description: {
                        callback: {
                            message: 'The description is required and cannot be empty',
                            callback: function (input) {
                                const code = $('[name="description"]').summernote('code');
                                // <p><br> is code generated by Summernote for empty content
                                return code !== '' && code !== '<p><br>';
                            },
                        },
                        validators: {
                            notEmpty: {
                                message: 'The description is required.'
                            }
                        }
                    },
                    published_date: {
                        validators: {
                            notEmpty: {
                                message: 'Published date is required.'
                            },
                            date: {
                                format: 'YYYY-MM-DD',
                                message: 'Published date must be a valid date.'
                            }
                        }
                    },
                    expiry_date: {
                        validators: {
                            notEmpty: {
                                message: 'Expiry date is required.'
                            },
                            date: {
                                format: 'YYYY-MM-DD',
                                message: 'Expiry date must be a valid date.'
                            }
                        }
                    },
                    attachment: {
                        validators: {
                            file: {
                                extension: 'jpeg,jpg,png,pdf',
                                type: 'image/jpeg,image/png,application/pdf',
                                maxSize: '2097152',
                                message: 'The selected file is not valid type or must not be greater than 2 MB.',
                            },
                        },
                    },
                },
                plugins: {
                    trigger: new FormValidation.plugins.Trigger(),
                    bootstrap5: new FormValidation.plugins.Bootstrap5(),
                    submitButton: new FormValidation.plugins.SubmitButton(),
                    defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                    icon: new FormValidation.plugins.Icon({
                        valid: 'bi bi-check2-square',
                        invalid: 'bi bi-x-lg',
                        validating: 'bi bi-arrow-repeat'
                    }),
                    startEndDate: new FormValidation.plugins.StartEndDate({
                        format: 'YYYY-MM-DD',
                        startDate: {
                            field: 'published_date',
                            message: 'Published date must be a valid date and earlier than expiry date.',
                        },
                        endDate: {
                            field: 'expiry_date',
                            message: 'Expiry date must be a valid date and later than from published date.',
                        },
                    }),
                }
            });

            $('[name="published_date"]').datepicker({
                language: 'en-GB',
                autoHide: true,
                format: 'yyyy-mm-dd',
            }).on('change', function (e) {
                fv.revalidateField('published_date');
            });

            $('[name="expiry_date"]').datepicker({
                language: 'en-GB',
                autoHide: true,
                format: 'yyyy-mm-dd',
            }).on('change', function (e) {
                fv.revalidateField('expiry_date');
            });

            $('[name="description"]')
                .summernote({
                    height: 400,
                })
                .on('summernote.change', function (customEvent, contents, $editable) {
                    // Revalidate the content when its value is changed by Summernote
                    fv.revalidateField('description');
                });

        });

    </script>
@endsection

@section('page-content')
<div class="m-content p-3">
    <div class="container-fluid">
        <div class="page-header pb-3 mb-3 border-bottom">
            <div class="d-flex flex-column flex-lg-row align-items-start align-items-lg-center gap-2">
            <div class="brd-crms flex-grow-1">
                <nav aria-label="breadcrumb">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item">
                                <a href="{!! route('dashboard.index') !!}" class="text-decoration-none text-dark">Home</a>
                            </li>
                            <li class="breadcrumb-item" aria-current="page">
                                <a href="{{route('announcement.index')}}" class="text-decoration-none">Announcement</a>
                            </li>
                            <li class="breadcrumb-item" aria-current="page">@yield('title')</li>
                        </ol>
                    </nav>
                    <h4 class="m-0 lh1 mt-1 fs-6 text-uppercase fw-bold text-primary">@yield('title')</h4>
                </div>
            </div>
        </div>

        <section>
            <form action="{{route('announcement.update', $announcement->id)}}" method="POST" id="announcementUpdateForm" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="card">
                    <div class="card-header fw-bold">
                        <h6 class="card-title">
                            Edit Announcement
                        </h6>
                    </div>

                    <div class="card-body">

                        <div class="row mb-2">
                            <div class="col-lg-6">
                                <label class="form-label" for="title">Title</label>
                                <input class="form-control" type="text" name="title" id="title" value="{{$announcement->title}}">
                            </div>
                        </div>

                        <div class="row mb-2">
                            <div class="col-lg-6">
                                <label class="form-label" for="description">Description</label>
                                <textarea class="form-control" name="description" id="description" cols="30" rows="10">{{$announcement->description}}</textarea>
                            </div>
                        </div>

                        <div class="row mb-2">
                            <div class="col-lg-6">
                                <label class="form-label" for="attachment">Attachment</label>
                                <input class="form-control" type="file" name="attachment" id="attachment">
                                <small>Supported file types jpeg/jpg/png/pdf and file size of upto 2MB.</small>
                                @if ($errors->has('attachment'))
                                    <span class="text-danger">{{$errors->first('attachment')}}</span>
                                @endif
                            </div>
                        </div>

                        <div class="row mb-2">
                            <div class="col-lg-6">
                                <label class="form-label" for="published_date">Published Date</label>
                                <input class="form-control" type="text" name="published_date" id="published_date" value="{{$announcement->published_date?->format('Y-m-d')}}">
                                @error('published_date')
                                    <div class="fv-plugins-message-container invalid-feedback">
                                        <div data-field="published_date">
                                            {{ $errors->first('published_date') }}
                                        </div>
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-2">
                            <div class="col-lg-6">
                                <label class="form-label" for="expiry_date">Expiry Date</label>
                                <input class="form-control" type="text" name="expiry_date" id="expiry_date" value="{{$announcement->expiry_date?->format('Y-m-d')}}">
                                @error('expiry_date')
                                    <div class="fv-plugins-message-container invalid-feedback">
                                        <div data-field="expiry_date">
                                            {{ $errors->first('expiry_date') }}
                                        </div>
                                    </div>
                                @enderror
                            </div>
                        </div>

                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary">Update</button>
                        <a href="{{route('announcement.index')}}" role="button" class="btn btn-sm btn-secondary">Cancel</a>
                    </div>
                </div>
            </form>
        </section>

    </div>
</div>

@stop
