<?php

return [
    'modules' => [
        'Announcement',
        'AssetDisposition',
        'Attachment',
        'Contract',
        'Employee',
        'EmployeeAttendance',
        'EmployeeExit',
        'EventCompletion',
        'ExitStaffClearance',
        'FundRequest',
        'GoodRequest',
        'Inventory',
        'LeaveRequest',
        'LieuLeave',
        'MaintenanceRequest',
        'Master',
        'MeetingHallBooking',
        'OffDayWork',
        'PerformanceReview',
        'Privilege',
        'ProbationaryReview',
        'Profile',
        'Project',
        'Report',
        'Supplier',
        'TravelAuthorization',
        'TravelRequest',
        'VehicleRequest',
        'WorkFromHome',
        'WorkLog'
    ],
];
